tosca_definitions_version: cloudify_dsl_1_4

description: Deploys the Prometheus Operator using the official manifests

imports:
  - https://cloudify.co/spec/cloudify/6.4.0/types.yaml
  - plugin:cloudify-utilities-plugin
  - plugin:cloudify-kubernetes-plugin

inputs:

  kubernetes_api_endpoint:
    type: string
    display_label: Kubernetes API Endpoint
    default: { get_environment_capability: kubernetes_cluster_host }

  kubernetes_token:
    type: string
    display_label: Kubernetes Service Account Token
    default: { get_environment_capability: token }

  kubernetes_ca_cert:
    type: string
    display_label: Kubernetes CA Certificate
    default: { get_environment_capability: ssl_ca_cert }

  kubernetes_client_config:
    display_label: Kubernetes plugin client configuration
    hidden: true
    description: >
     Configuration for Kubernetes client. Can be left at default values.
    default:
      configuration:
        api_options:
          host: { get_input: kubernetes_api_endpoint }
          api_key: { get_input: kubernetes_token }
          ssl_ca_cert: { get_input: kubernetes_ca_cert }
          debug: true
          verify_ssl: true

node_templates:

  prometheus_operator:
    type: cloudify.nodes.Root
    interfaces:
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: scripts/kubectl_apply.sh
          executor: central_deployment_agent
          inputs: &kubectl_inputs
            host: { get_input: kubernetes_api_endpoint }
            token: { get_input: kubernetes_token }
        delete:
          implementation: scripts/kubectl_delete.sh
          executor: central_deployment_agent
          inputs: *kubectl_inputs
