kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: abort-chaos
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: python-prometheus
  mode: all
  target: Request
  abort: true
  port: 8080
  path: /
  duration: 2m
