apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-prometheus
  name: demo-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: python-prometheus
  type: LoadBalancer
